In [1]:
import numpy as np
import random

In [6]:

np_arang=np.arange(10,20,2,dtype=int)
print('arange创建np_arang:',np_arang)
print('arange创建np_arang的元素类型:',np_arang.dtype)
print('arange创建np_arang的类型:',type(np_arang))

arange创建np_arang: [10 12 14 16 18]
arange创建np_arang的元素类型: int64
arange创建np_arang的类型: <class 'numpy.ndarray'>


## 随机数生成ndarray对象

In [8]:

arr1=np.random.rand(3,2)
print(arr1)

[[0.91076696 0.21306462]
 [0.13885279 0.16880641]
 [0.21342491 0.66367121]]


In [10]:
arr_int=np.random.randint(0,10,(3,5))
print(arr_int)

[[3 1 4 1 2]
 [3 3 8 8 8]
 [5 5 6 0 2]]


## numpy的类型转换 astype

In [11]:
arr3=np.arange(0,10,2,dtype=np.int32)
print(arr3)
print(arr3.dtype)

[0 2 4 6 8]
int32


In [12]:
arr4=arr3.astype(np.float32)
print(arr4)

[0. 2. 4. 6. 8.]


## 等比/等差数列

In [14]:
a=np.logspace(0,9,10,base=2)
print(a)

[  1.   2.   4.   8.  16.  32.  64. 128. 256. 512.]


## 基本函数

In [3]:
#1. 创建标准的正态分布序列
arr=np.random.randn(3,4)
print(arr)

[[-0.95729828  0.51129008 -1.17823045 -0.26403155]
 [ 0.49543471  0.20041901  1.18952282  0.7231277 ]
 [ 0.38121964  0.33016438  0.10299155  0.10134868]]


In [8]:
#2. 测试基本函数
# print(np.ceil(arr))       #天花板，向上取整
# print(np.floor(arr))
# print(np.rint(arr))
# print(np.abs(arr))
print(np.multiply(arr,arr))

[[0.91642    0.26141755 1.38822698 0.06971266]
 [0.24545555 0.04016778 1.41496453 0.52291366]
 [0.14532842 0.10900851 0.01060726 0.01027155]]


## 统计函数

In [13]:
#1. 创建ndarray对象
arr=np.arange(12).reshape(3,4)
print(arr)



[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [16]:
#cumsum累加和 ，cumprod累乘积
a_cumsum=np.cumsum(arr)
print(a_cumsum)

[ 0  1  3  6 10 15 21 28 36 45 55 66]


In [17]:
print(np.cumprod(arr))

[0 0 0 0 0 0 0 0 0 0 0 0]


In [18]:
print(np.sum(arr))

66


In [19]:
print(np.mean(arr))

5.5


In [20]:
print(np.max(arr))

11


In [21]:
print(np.min(arr))

0


In [22]:
print(np.std(arr))

3.452052529534663


## 矩阵运算

In [4]:
#1.定义数组
arr1=np.array([10,20,30,40])
arr2=np.arange(4)
print(f'arr2:{arr1}')
print(f'arr2:{arr2}')

arr2:[10 20 30 40]
arr2:[0 1 2 3]


In [5]:
#减法运算
print(arr1-arr2)

[10 19 28 37]


In [6]:
#加法运算
print(arr1+arr2)

[10 21 32 43]


### 矩阵乘法

In [9]:
#行列数一致
print(arr1@arr2)
print(np.dot(arr1,arr2))
print(arr1.dot(arr2))
# print(arr1*arr2)

200
200
200


In [14]:
arr3=np.array([
    [1,2,3],[4,5,6]
])
arr4=np.array([[8,9],[6,5],[3,2]])
print(arr3)
print(arr4)

#2.行列数不一致
print(np.dot(arr3,arr4))

[[1 2 3]
 [4 5 6]]
[[8 9]
 [6 5]
 [3 2]]
[[29 25]
 [80 73]]


[[29 25]
 [80 73]]
